[TS-696] Added verification the order of repeating groups
th2-net/th2-check1 pull request #58
Opened 2021-09-15 11:29 UTC by yarchiksmith

2021-09-22 11:58 UTC, Nikita-Smirnov-Exactpro requested changes

2021-09-22 11:58 UTC, Nikita-Smirnov-Exactpro commented on src/main/kotlin/com/exactpro/th2/check1/rule/AbstractCheckTask.kt
> +            }
```suggestion
            it.ignoredFields = this.comparisonSettings.ignoreFieldsList.toSet()
            it.isKeepResultGroupOrder = true
```

2021-09-22 11:58 UTC, Nikita-Smirnov-Exactpro commented on src/test/kotlin/com/exactpro/th2/check1/rule/check/TestCheckRuleTask.kt
> +            assertEquals(1, verificationEvents.size)
How do we check the order of repeating groups if we submit only one filter?
checke1 sorts in order to increase the number of FAILED fields in the previous version.
Let's make a message with two group filters:
* both fields are failed
* the only one filed failed
and run it vs two messages which have (A, B) and (B, A) order of the repeating group.
The order of results will be equivalent the order in message

2021-09-24 09:18 UTC, OptimumOpium commented on src/test/kotlin/com/exactpro/th2/check1/rule/check/TestCheckRuleTask.kt
> +    }
Where do you use this?

2021-09-28 12:47 UTC, OptimumOpium approved these changes

2021-09-28 12:49 UTC, yarchiksmith commented
@Nikita-Smirnov-Exactpro Could you approve these changes?

2021-09-28 13:13 UTC, merged